<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="grid_tests.GridTest-20220122082734" tests="1" file="grid_tests.py" time="0.004" timestamp="2022-01-22T08:27:35" failures="1" errors="0" skipped="0">
	<testcase classname="grid_tests.GridTest" name="test_create_grid_from_text_file" time="0.004" timestamp="2022-01-22T08:27:35">
		<failure type="AssertionError" message="'y' != 'x'
- y
+ x
"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Program Files\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Program Files\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "c:\users\gabri\onedrive\documents\personalprojects\word-grid-finder\src\unittest\python\grid_tests.py", line 22, in test_create_grid_from_text_file
    self.assertEquals("y", cell_0_0.get_letter())
  File "C:\Program Files\Python310\lib\unittest\case.py", line 1344, in deprecated_func
    return original_func(*args, **kwargs)
  File "C:\Program Files\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Program Files\Python310\lib\unittest\case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Program Files\Python310\lib\unittest\case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: 'y' != 'x'
- y
+ x

]]></failure>
	</testcase>
</testsuite>
